//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class JTEEntities : DbContext
    {
        public JTEEntities()
            : base("name=JTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<JK_GUEST> JK_GUEST { get; set; }
        public DbSet<JK_GUEST_OUT> JK_GUEST_OUT { get; set; }
        public DbSet<QRTZ_BLOB_TRIGGERS> QRTZ_BLOB_TRIGGERS { get; set; }
        public DbSet<QRTZ_CALENDARS> QRTZ_CALENDARS { get; set; }
        public DbSet<QRTZ_CRON_TRIGGERS> QRTZ_CRON_TRIGGERS { get; set; }
        public DbSet<QRTZ_FIRED_TRIGGERS> QRTZ_FIRED_TRIGGERS { get; set; }
        public DbSet<QRTZ_JOB_DETAILS> QRTZ_JOB_DETAILS { get; set; }
        public DbSet<QRTZ_LOCKS> QRTZ_LOCKS { get; set; }
        public DbSet<QRTZ_PAUSED_TRIGGER_GRPS> QRTZ_PAUSED_TRIGGER_GRPS { get; set; }
        public DbSet<QRTZ_SCHEDULER_STATE> QRTZ_SCHEDULER_STATE { get; set; }
        public DbSet<QRTZ_SIMPLE_TRIGGERS> QRTZ_SIMPLE_TRIGGERS { get; set; }
        public DbSet<QRTZ_SIMPROP_TRIGGERS> QRTZ_SIMPROP_TRIGGERS { get; set; }
        public DbSet<QRTZ_TRIGGERS> QRTZ_TRIGGERS { get; set; }
        public DbSet<T_GuestInfo> T_GuestInfo { get; set; }
        public DbSet<T_GuestInfo_log> T_GuestInfo_log { get; set; }
        public DbSet<t_h_account_book> t_h_account_book { get; set; }
        public DbSet<t_h_accounts> t_h_accounts { get; set; }
        public DbSet<t_h_bank_account> t_h_bank_account { get; set; }
        public DbSet<t_h_bill_no_maintenance> t_h_bill_no_maintenance { get; set; }
        public DbSet<t_h_bill_related> t_h_bill_related { get; set; }
        public DbSet<t_h_blob> t_h_blob { get; set; }
        public DbSet<t_h_business> t_h_business { get; set; }
        public DbSet<t_h_business_remark> t_h_business_remark { get; set; }
        public DbSet<t_h_change_order> t_h_change_order { get; set; }
        public DbSet<t_h_checkinAnalysisByGuest> t_h_checkinAnalysisByGuest { get; set; }
        public DbSet<t_h_checkinAnalysisByRoomtype> t_h_checkinAnalysisByRoomtype { get; set; }
        public DbSet<t_h_checkinAnalysisByStandand> t_h_checkinAnalysisByStandand { get; set; }
        public DbSet<t_h_dept> t_h_dept { get; set; }
        public DbSet<t_h_empl> t_h_empl { get; set; }
        public DbSet<t_h_event_main> t_h_event_main { get; set; }
        public DbSet<t_h_event_point_exch_room> t_h_event_point_exch_room { get; set; }
        public DbSet<t_h_event_point_exch_room_log> t_h_event_point_exch_room_log { get; set; }
        public DbSet<t_h_event_room_price> t_h_event_room_price { get; set; }
        public DbSet<t_h_event_target> t_h_event_target { get; set; }
        public DbSet<t_h_forward_price_medi> t_h_forward_price_medi { get; set; }
        public DbSet<t_h_forward_price_medi_history> t_h_forward_price_medi_history { get; set; }
        public DbSet<t_h_forward_price_medi_temp> t_h_forward_price_medi_temp { get; set; }
        public DbSet<t_h_forward_price_member> t_h_forward_price_member { get; set; }
        public DbSet<t_h_forward_price_member_history> t_h_forward_price_member_history { get; set; }
        public DbSet<t_h_forward_price_member_temp> t_h_forward_price_member_temp { get; set; }
        public DbSet<t_h_forward_price_unit> t_h_forward_price_unit { get; set; }
        public DbSet<t_h_forward_price_unit_history> t_h_forward_price_unit_history { get; set; }
        public DbSet<t_h_forward_price_unit_temp> t_h_forward_price_unit_temp { get; set; }
        public DbSet<t_h_history_order_price> t_h_history_order_price { get; set; }
        public DbSet<t_h_hotel> t_h_hotel { get; set; }
        public DbSet<t_h_link> t_h_link { get; set; }
        public DbSet<t_h_live_order_price> t_h_live_order_price { get; set; }
        public DbSet<t_h_log> t_h_log { get; set; }
        public DbSet<t_h_module_const> t_h_module_const { get; set; }
        public DbSet<t_h_obj_blob> t_h_obj_blob { get; set; }
        public DbSet<t_h_permission> t_h_permission { get; set; }
        public DbSet<t_h_policeinterface> t_h_policeinterface { get; set; }
        public DbSet<t_h_print_history> t_h_print_history { get; set; }
        public DbSet<t_h_reserve_order_price> t_h_reserve_order_price { get; set; }
        public DbSet<t_h_role> t_h_role { get; set; }
        public DbSet<t_h_role_perm> t_h_role_perm { get; set; }
        public DbSet<t_h_serial> t_h_serial { get; set; }
        public DbSet<t_h_shift> t_h_shift { get; set; }
        public DbSet<t_h_standard> t_h_standard { get; set; }
        public DbSet<t_h_sys_constant> t_h_sys_constant { get; set; }
        public DbSet<t_h_sys_hz> t_h_sys_hz { get; set; }
        public DbSet<t_h_template> t_h_template { get; set; }
        public DbSet<t_h_template_detail> t_h_template_detail { get; set; }
        public DbSet<t_h_unit_account> t_h_unit_account { get; set; }
        public DbSet<t_h_updatelog> t_h_updatelog { get; set; }
        public DbSet<t_h_user> t_h_user { get; set; }
        public DbSet<t_h_user_hotel> t_h_user_hotel { get; set; }
        public DbSet<t_h_user_role> t_h_user_role { get; set; }
        public DbSet<t_h_xml_updown> t_h_xml_updown { get; set; }
        public DbSet<t_h_yserver_clicent> t_h_yserver_clicent { get; set; }
        public DbSet<t_m_accrule> t_m_accrule { get; set; }
        public DbSet<t_m_activities> t_m_activities { get; set; }
        public DbSet<t_m_amountpresentrule> t_m_amountpresentrule { get; set; }
        public DbSet<t_m_changecardlog> t_m_changecardlog { get; set; }
        public DbSet<t_m_pointexchangelog> t_m_pointexchangelog { get; set; }
        public DbSet<t_m_pointexchangerule> t_m_pointexchangerule { get; set; }
        public DbSet<t_m_pointlog> t_m_pointlog { get; set; }
        public DbSet<t_m_promotionlog> t_m_promotionlog { get; set; }
        public DbSet<t_m_promotionrule> t_m_promotionrule { get; set; }
        public DbSet<t_m_relationmemberstandard> t_m_relationmemberstandard { get; set; }
        public DbSet<t_m_storevaluemode> t_m_storevaluemode { get; set; }
        public DbSet<t_r_anomaly> t_r_anomaly { get; set; }
        public DbSet<t_r_building> t_r_building { get; set; }
        public DbSet<t_r_global_lockpara> t_r_global_lockpara { get; set; }
        public DbSet<t_r_holiday_price> t_r_holiday_price { get; set; }
        public DbSet<t_r_hour_room> t_r_hour_room { get; set; }
        public DbSet<t_r_hour_room_price> t_r_hour_room_price { get; set; }
        public DbSet<t_r_lock_record> t_r_lock_record { get; set; }
        public DbSet<t_r_repair_plan> t_r_repair_plan { get; set; }
        public DbSet<t_r_room> t_r_room { get; set; }
        public DbSet<t_r_room_state_log> t_r_room_state_log { get; set; }
        public DbSet<t_r_room_type> t_r_room_type { get; set; }
        public DbSet<t_r_special_room> t_r_special_room { get; set; }
        public DbSet<t_r_special_room_price> t_r_special_room_price { get; set; }
        public DbSet<t_s_field> t_s_field { get; set; }
        public DbSet<t_s_queue> t_s_queue { get; set; }
        public DbSet<t_s_registerInfo> t_s_registerInfo { get; set; }
        public DbSet<t_s_templet> t_s_templet { get; set; }
        public DbSet<t_s_templetcontent> t_s_templetcontent { get; set; }
        public DbSet<t_u_check_in_log> t_u_check_in_log { get; set; }
        public DbSet<t_u_deposit> t_u_deposit { get; set; }
        public DbSet<t_u_guest> t_u_guest { get; set; }
        public DbSet<t_u_guests_goods_management> t_u_guests_goods_management { get; set; }
        public DbSet<t_u_history_order> t_u_history_order { get; set; }
        public DbSet<t_u_lease_manger> t_u_lease_manger { get; set; }
        public DbSet<t_u_lease_mangert_rela> t_u_lease_mangert_rela { get; set; }
        public DbSet<t_u_male_pay> t_u_male_pay { get; set; }
        public DbSet<t_u_med_rake_back> t_u_med_rake_back { get; set; }
        public DbSet<t_u_medi> t_u_medi { get; set; }
        public DbSet<t_u_member> t_u_member { get; set; }
        public DbSet<t_u_member_type> t_u_member_type { get; set; }
        public DbSet<t_u_order> t_u_order { get; set; }
        public DbSet<t_u_order_rela> t_u_order_rela { get; set; }
        public DbSet<t_u_parking_lot> t_u_parking_lot { get; set; }
        public DbSet<t_u_parking_management> t_u_parking_management { get; set; }
        public DbSet<t_u_pay_method> t_u_pay_method { get; set; }
        public DbSet<t_u_project_rela> t_u_project_rela { get; set; }
        public DbSet<t_u_protocol_price> t_u_protocol_price { get; set; }
        public DbSet<t_u_protocol_unit> t_u_protocol_unit { get; set; }
        public DbSet<t_u_reserve> t_u_reserve { get; set; }
        public DbSet<t_u_reserve_room> t_u_reserve_room { get; set; }
        public DbSet<t_u_room_price> t_u_room_price { get; set; }
        public DbSet<t_u_settlement> t_u_settlement { get; set; }
        public DbSet<t_u_taxi_registra> t_u_taxi_registra { get; set; }
        public DbSet<t_u_team> t_u_team { get; set; }
        public DbSet<t_u_unit_medi_type> t_u_unit_medi_type { get; set; }
        public DbSet<t_u_wake_service> t_u_wake_service { get; set; }
        public DbSet<t_w_allot_detail> t_w_allot_detail { get; set; }
        public DbSet<t_w_goods> t_w_goods { get; set; }
        public DbSet<t_w_goods_category> t_w_goods_category { get; set; }
        public DbSet<t_w_goods_in> t_w_goods_in { get; set; }
        public DbSet<t_w_goods_in_detail> t_w_goods_in_detail { get; set; }
        public DbSet<t_w_goods_out> t_w_goods_out { get; set; }
        public DbSet<t_w_goods_out_detail> t_w_goods_out_detail { get; set; }
        public DbSet<t_w_goods_store> t_w_goods_store { get; set; }
        public DbSet<t_w_goods_unit> t_w_goods_unit { get; set; }
        public DbSet<t_w_inventory> t_w_inventory { get; set; }
        public DbSet<t_w_inventory_detail> t_w_inventory_detail { get; set; }
        public DbSet<t_w_loss_overflow> t_w_loss_overflow { get; set; }
        public DbSet<t_w_loss_overflow_detail> t_w_loss_overflow_detail { get; set; }
        public DbSet<t_w_sale> t_w_sale { get; set; }
        public DbSet<t_w_store_allot> t_w_store_allot { get; set; }
        public DbSet<t_w_supplier> t_w_supplier { get; set; }
        public DbSet<t_w_supplier_schedule> t_w_supplier_schedule { get; set; }
        public DbSet<t_w_unit_account> t_w_unit_account { get; set; }
        public DbSet<t_w_warehouse> t_w_warehouse { get; set; }
        public DbSet<t_w_warehouse_admin> t_w_warehouse_admin { get; set; }
        public DbSet<t_h_authorization_third> t_h_authorization_third { get; set; }
        public DbSet<t_h_credit_settle_record> t_h_credit_settle_record { get; set; }
        public DbSet<t_h_inint> t_h_inint { get; set; }
        public DbSet<t_h_invoice_records> t_h_invoice_records { get; set; }
        public DbSet<t_h_message> t_h_message { get; set; }
        public DbSet<t_h_phone> t_h_phone { get; set; }
        public DbSet<t_m_pointsrule> t_m_pointsrule { get; set; }
        public DbSet<t_u_breakfast_voucher> t_u_breakfast_voucher { get; set; }
        public DbSet<t_u_clock> t_u_clock { get; set; }
        public DbSet<t_u_male_model> t_u_male_model { get; set; }
        public DbSet<t_u_notebook> t_u_notebook { get; set; }
        public DbSet<t_u_together> t_u_together { get; set; }
        public DbSet<ThridSetting> ThridSettings { get; set; }
        public DbSet<TINTERNALGUEST> TINTERNALGUESTS { get; set; }
        public DbSet<TOVERSEASGUEST> TOVERSEASGUESTS { get; set; }
        public DbSet<AllOrderRela> AllOrderRelas { get; set; }
    
        public virtual ObjectResult<string> GetBillNo(string serialCode, string hotelCode)
        {
            var serialCodeParameter = serialCode != null ?
                new ObjectParameter("SerialCode", serialCode) :
                new ObjectParameter("SerialCode", typeof(string));
    
            var hotelCodeParameter = hotelCode != null ?
                new ObjectParameter("HotelCode", hotelCode) :
                new ObjectParameter("HotelCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetBillNo", serialCodeParameter, hotelCodeParameter);
        }
    
        public virtual ObjectResult<string> GetBillNoNew(string serialCode)
        {
            var serialCodeParameter = serialCode != null ?
                new ObjectParameter("SerialCode", serialCode) :
                new ObjectParameter("SerialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetBillNoNew", serialCodeParameter);
        }
    
        public virtual int GetRegisterCode(string registerCode)
        {
            var registerCodeParameter = registerCode != null ?
                new ObjectParameter("RegisterCode", registerCode) :
                new ObjectParameter("RegisterCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRegisterCode", registerCodeParameter);
        }
    
        public virtual ObjectResult<string> GetSerialNo(string serialCode)
        {
            var serialCodeParameter = serialCode != null ?
                new ObjectParameter("SerialCode", serialCode) :
                new ObjectParameter("SerialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetSerialNo", serialCodeParameter);
        }
    
        public virtual ObjectResult<string> GetSerialNoNew(string serialCode)
        {
            var serialCodeParameter = serialCode != null ?
                new ObjectParameter("SerialCode", serialCode) :
                new ObjectParameter("SerialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetSerialNoNew", serialCodeParameter);
        }
    
        public virtual int p_backupdb(string dbname, string bkpath, string bkfname, string bktype, Nullable<bool> appendfile, string password)
        {
            var dbnameParameter = dbname != null ?
                new ObjectParameter("dbname", dbname) :
                new ObjectParameter("dbname", typeof(string));
    
            var bkpathParameter = bkpath != null ?
                new ObjectParameter("bkpath", bkpath) :
                new ObjectParameter("bkpath", typeof(string));
    
            var bkfnameParameter = bkfname != null ?
                new ObjectParameter("bkfname", bkfname) :
                new ObjectParameter("bkfname", typeof(string));
    
            var bktypeParameter = bktype != null ?
                new ObjectParameter("bktype", bktype) :
                new ObjectParameter("bktype", typeof(string));
    
            var appendfileParameter = appendfile.HasValue ?
                new ObjectParameter("appendfile", appendfile) :
                new ObjectParameter("appendfile", typeof(bool));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_backupdb", dbnameParameter, bkpathParameter, bkfnameParameter, bktypeParameter, appendfileParameter, passwordParameter);
        }
    
        public virtual int sp_GetForwardPrice(Nullable<System.DateTime> begindate, Nullable<System.DateTime> enddate, Nullable<short> flag, string hotelcode, string code, string name)
        {
            var begindateParameter = begindate.HasValue ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(short));
    
            var hotelcodeParameter = hotelcode != null ?
                new ObjectParameter("hotelcode", hotelcode) :
                new ObjectParameter("hotelcode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetForwardPrice", begindateParameter, enddateParameter, flagParameter, hotelcodeParameter, codeParameter, nameParameter);
        }
    
        public virtual int sp_page_GetForwardPrice(Nullable<System.DateTime> begindate, Nullable<System.DateTime> enddate, Nullable<short> flag, string hotelcode, string code, string name, Nullable<int> pagesize, Nullable<int> pageindex, ObjectParameter pagecount, ObjectParameter recordcount)
        {
            var begindateParameter = begindate.HasValue ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(short));
    
            var hotelcodeParameter = hotelcode != null ?
                new ObjectParameter("hotelcode", hotelcode) :
                new ObjectParameter("hotelcode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            var pageindexParameter = pageindex.HasValue ?
                new ObjectParameter("pageindex", pageindex) :
                new ObjectParameter("pageindex", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_page_GetForwardPrice", begindateParameter, enddateParameter, flagParameter, hotelcodeParameter, codeParameter, nameParameter, pagesizeParameter, pageindexParameter, pagecount, recordcount);
        }
    }
}
