//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class JK_GUEST_OUT
    {
        public int ID { get; set; }
        public string GUESTID { get; set; }
        public string GUESTTYPE { get; set; }
        public string ROOMID { get; set; }
        public string OUTORCHG { get; set; }
        public string ETIME { get; set; }
        public string EWAITER { get; set; }
        public string OK { get; set; }
    }
}
