//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class JK_GUEST
    {
        public int ID { get; set; }
        public string GUESTID { get; set; }
        public string GUESTTYPE { get; set; }
        public string GROUPID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string BIRTHDAY { get; set; }
        public string IDTYPE { get; set; }
        public string IDCODE { get; set; }
        public string DISTRICTID { get; set; }
        public string ADDRESS { get; set; }
        public string HOTELID { get; set; }
        public string ROOMID { get; set; }
        public string LTIME { get; set; }
        public string LWAITER { get; set; }
        public string ETIME { get; set; }
        public string EWAITER { get; set; }
        public byte[] PHOTO { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string COUNTRY { get; set; }
        public string NATION { get; set; }
        public string CARDTYPE { get; set; }
        public string CARDID { get; set; }
        public string VISATYPE { get; set; }
        public string VISACODE { get; set; }
        public string VISADATE { get; set; }
        public string VISAORGAN { get; set; }
        public string INDATE { get; set; }
        public string INPORT { get; set; }
        public string RECEPTIONORGAN { get; set; }
        public string SUMMARY { get; set; }
        public string STATUS { get; set; }
        public string CREATETIME { get; set; }
        public string SCANTIME { get; set; }
        public byte[] IDPHOTO { get; set; }
        public string TOWHERE { get; set; }
        public string FROMWHERE { get; set; }
        public string CREDITTYPE { get; set; }
        public string CREDITID { get; set; }
        public string OK { get; set; }
    }
}
