//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_SIMPLE_TRIGGERS
    {
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public long REPEAT_COUNT { get; set; }
        public long REPEAT_INTERVAL { get; set; }
        public long TIMES_TRIGGERED { get; set; }
        public string SCHED_NAME { get; set; }
    
        public virtual QRTZ_TRIGGERS QRTZ_TRIGGERS { get; set; }
    }
}
