//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_ChatMessage
    {
        public int ID { get; set; }
        public string SendUserCode { get; set; }
        public string ReceiveUserCode { get; set; }
        public string Content { get; set; }
        public bool IsReceive { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string delusers { get; set; }
    }
}
