//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_View_SaleDetail
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string ClassID { get; set; }
        public int BrandID { get; set; }
        public int BuyCount { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime AddDate { get; set; }
        public string UserName { get; set; }
    }
}
