//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_UserCoupon
    {
        public int ID { get; set; }
        public int CouponID { get; set; }
        public int GetType { get; set; }
        public string Number { get; set; }
        public string Password { get; set; }
        public int IsUse { get; set; }
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
    }
}
