//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_Upload
    {
        public int ID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string UploadName { get; set; }
        public string OtherFile { get; set; }
        public Nullable<int> Size { get; set; }
        public string FileType { get; set; }
        public string RandomNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string IP { get; set; }
    }
}
