//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Email { get; set; }
        public int Sex { get; set; }
        public string Introduce { get; set; }
        public string Photo { get; set; }
        public string MSN { get; set; }
        public string QQ { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string RegionID { get; set; }
        public string Address { get; set; }
        public string Birthday { get; set; }
        public string RegisterIP { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string LastLoginIP { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public int LoginTimes { get; set; }
        public string SafeCode { get; set; }
        public System.DateTime FindDate { get; set; }
        public int Status { get; set; }
        public string OpenID { get; set; }
        public System.DateTime onlinetime { get; set; }
        public Nullable<int> PurchaseStatus { get; set; }
        public string PurchaseName { get; set; }
        public string PurchaseEmail { get; set; }
        public string PurchaseMobile { get; set; }
        public string PurchaseTel { get; set; }
        public string PurchaseIDCard { get; set; }
        public string PurchaseIntroduce { get; set; }
        public string PurchaseIDCardImgurl { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    }
}
