//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_BookingProduct
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string RelationUser { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string UserNote { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string BookingIP { get; set; }
        public int IsHandler { get; set; }
        public System.DateTime HandlerDate { get; set; }
        public int HandlerAdminID { get; set; }
        public string HandlerAdminName { get; set; }
        public string HandlerNote { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
    }
}
