//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_Shop
    {
        public int SId { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string ClassID { get; set; }
        public string ShopName { get; set; }
        public string ShopNum { get; set; }
        public string ShopImage { get; set; }
        public string ShopIntroduction { get; set; }
        public string BusinessLicense { get; set; }
        public string ShopAddress { get; set; }
        public string ShopQQ { get; set; }
        public string ShopTel { get; set; }
        public Nullable<decimal> MinimumAmount { get; set; }
        public string DeliveryTime { get; set; }
        public string DeliveryRange { get; set; }
        public string Announcement { get; set; }
        public Nullable<System.DateTime> OpeningTime { get; set; }
        public Nullable<int> ShopStatus { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string ShopTemplate { get; set; }
        public string PointLng { get; set; }
        public string PointLat { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<int> CollectCount { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> IsTop { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public Nullable<int> SumPoint { get; set; }
        public Nullable<decimal> PerPoint { get; set; }
        public int ShopState { get; set; }
        public System.DateTime StopTime { get; set; }
        public string IDCardFront { get; set; }
        public string IDCardReverse { get; set; }
        public int rz { get; set; }
        public int rb { get; set; }
        public long times { get; set; }
        public System.DateTime flogintime { get; set; }
        public System.DateTime elogintime { get; set; }
        public string Industry { get; set; }
        public string AddCol1 { get; set; }
        public Nullable<int> AddCol2 { get; set; }
        public Nullable<System.DateTime> AddCol3 { get; set; }
        public string ShopAdImg { get; set; }
        public string ComLiImg1 { get; set; }
        public string ComLiImg2 { get; set; }
        public string ComLiImg3 { get; set; }
        public string ComLiImg4 { get; set; }
    }
}
