//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_ShopCommet
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int ShopID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string UserIP { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> Support { get; set; }
        public Nullable<int> Against { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> ReplyCount { get; set; }
        public string AdminReplyContent { get; set; }
        public Nullable<System.DateTime> AdminReplyDate { get; set; }
    }
}
