//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Spelling { get; set; }
        public string Color { get; set; }
        public string FontStyle { get; set; }
        public string ProductNumber { get; set; }
        public string ClassID { get; set; }
        public int BrandID { get; set; }
        public decimal MarketPrice { get; set; }
        public int Weight { get; set; }
        public int SendPoint { get; set; }
        public string Photo { get; set; }
        public string Keywords { get; set; }
        public string Summary { get; set; }
        public string Introduction { get; set; }
        public string Remark { get; set; }
        public int IsSpecial { get; set; }
        public int IsNew { get; set; }
        public int IsHot { get; set; }
        public int IsSale { get; set; }
        public int IsTop { get; set; }
        public string Accessory { get; set; }
        public string RelationProduct { get; set; }
        public string RelationArticle { get; set; }
        public int ViewCount { get; set; }
        public int AllowComment { get; set; }
        public int CommentCount { get; set; }
        public int SumPoint { get; set; }
        public decimal PerPoint { get; set; }
        public int PhotoCount { get; set; }
        public int CollectCount { get; set; }
        public int TotalStorageCount { get; set; }
        public int OrderCount { get; set; }
        public int SendCount { get; set; }
        public int ImportActualStorageCount { get; set; }
        public int ImportVirtualStorageCount { get; set; }
        public int LowerCount { get; set; }
        public int UpperCount { get; set; }
        public int AttributeClassID { get; set; }
        public Nullable<int> StandardType { get; set; }
        public System.DateTime AddDate { get; set; }
        public long TaobaoID { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string SimpleDisc { get; set; }
        public string ProductPara { get; set; }
        public string ProductGg { get; set; }
        public string DanWei { get; set; }
        public string DescriptionTitle1 { get; set; }
        public string Description1 { get; set; }
        public string DescriptionTitle2 { get; set; }
        public string Description2 { get; set; }
        public string DescriptionTitle3 { get; set; }
        public string Description3 { get; set; }
    }
}
