//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocoShop_UserShopConfig
    {
        public long id { get; set; }
        public string Announcement { get; set; }
        public double Distribution { get; set; }
        public string SkinPath { get; set; }
        public int UserID { get; set; }
        public string ShopTitle { get; set; }
        public string KeyWorlds { get; set; }
        public string Discriptions { get; set; }
        public System.DateTime CreadeTime { get; set; }
        public string ShopNumber { get; set; }
        public string Address { get; set; }
        public double Cemmends { get; set; }
        public int ClassID { get; set; }
        public string mapxy { get; set; }
    }
}
