//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GuestInfo
    {
        public int id { get; set; }
        public string PERSONTYPE { get; set; }
        public string DAYID { get; set; }
        public string SourceID { get; set; }
        public string Accnt { get; set; }
        public string X_SN { get; set; }
        public string M_FN { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Nation { get; set; }
        public string P_NATIONAL { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Credentials { get; set; }
        public string CredentialsNo { get; set; }
        public string VISA_T { get; set; }
        public string VISA_NO { get; set; }
        public Nullable<System.DateTime> PASS_DATE { get; set; }
        public Nullable<System.DateTime> STAY_DATE { get; set; }
        public string SignDepartment { get; set; }
        public Nullable<System.DateTime> Enterdate { get; set; }
        public string EnterPort { get; set; }
        public string ReceiveUnit { get; set; }
        public string Come { get; set; }
        public string Gotow { get; set; }
        public string Reason { get; set; }
        public string City { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> PhotoLen { get; set; }
        public string Pym { get; set; }
        public string Credit_Code { get; set; }
        public string Credit_No { get; set; }
        public Nullable<System.DateTime> ROut_Time { get; set; }
        public Nullable<System.DateTime> RIn_Time { get; set; }
        public string Address { get; set; }
        public string GroupName { get; set; }
        public byte[] Photo { get; set; }
        public string Memo { get; set; }
        public Nullable<int> SendInfo { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
        public string Sta { get; set; }
        public string Type { get; set; }
    }
}
