//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_invoice_records
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string order_no { get; set; }
        public string room_no { get; set; }
        public string guest_name { get; set; }
        public Nullable<decimal> consume_amount { get; set; }
        public string invoice_no { get; set; }
        public string invoice_type { get; set; }
        public Nullable<decimal> invoice_amount { get; set; }
        public Nullable<decimal> invoice_tax { get; set; }
        public string invoice_operator { get; set; }
        public Nullable<System.DateTime> invoice_datetime { get; set; }
        public string invoice_remark { get; set; }
    }
}
