//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_credit_settle_record
    {
        public long id { get; set; }
        public string order_no { get; set; }
        public string room_no { get; set; }
        public Nullable<decimal> other_fee { get; set; }
        public Nullable<decimal> total_room_fee { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public Nullable<long> tid { get; set; }
        public string other_fee_detail { get; set; }
        public Nullable<int> flag { get; set; }
        public string hotel_code { get; set; }
    }
}
