//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_policeinterface
    {
        public long id { get; set; }
        public string orderno { get; set; }
        public string gasthauscode { get; set; }
        public string guestid { get; set; }
        public string archivesno { get; set; }
        public Nullable<System.DateTime> checkintime { get; set; }
        public string papertypeid { get; set; }
        public string paperid { get; set; }
        public string name { get; set; }
        public Nullable<int> sexid { get; set; }
        public string nationid { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string cityid { get; set; }
        public string address { get; set; }
        public string roomid { get; set; }
        public Nullable<int> checkinmodeid { get; set; }
        public Nullable<int> checkintypeid { get; set; }
        public Nullable<int> guesttype { get; set; }
        public Nullable<int> is2ndcard { get; set; }
        public string photostr { get; set; }
        public string username { get; set; }
        public string policeno { get; set; }
    }
}
