//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_yserver_clicent
    {
        public string table_s { get; set; }
        public string column_s { get; set; }
        public string table_c { get; set; }
        public string column_c { get; set; }
        public string pk_s { get; set; }
        public string desc_s { get; set; }
        public string yt { get; set; }
        public string pk_c { get; set; }
        public string datatype { get; set; }
        public Nullable<int> flag { get; set; }
        public long id { get; set; }
    }
}
