//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_hotel
    {
        public long id { get; set; }
        public string link_code { get; set; }
        public string hotel_code { get; set; }
        public string name { get; set; }
        public string linkman { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string web_addr { get; set; }
        public string reserve_tel { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> service_date { get; set; }
        public string qly_hotel_code { get; set; }
        public string regcode { get; set; }
        public string version_type { get; set; }
        public Nullable<System.DateTime> use_date { get; set; }
        public int client_num { get; set; }
        public string provinceCode { get; set; }
        public string cityCode { get; set; }
        public string hotelGroupCode { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> lastModifyTime { get; set; }
        public string salesman { get; set; }
        public string sellerId { get; set; }
        public string classCode { get; set; }
        public string hotelTypeCode { get; set; }
        public string version { get; set; }
        public string sms_sign { get; set; }
        public string zhhotelcode { get; set; }
    }
}
