//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_account_book
    {
        public long id { get; set; }
        public string archives_no { get; set; }
        public Nullable<int> custome_type { get; set; }
        public string account_book_code { get; set; }
        public string account_book_name { get; set; }
        public Nullable<decimal> gua_moeny { get; set; }
        public Nullable<decimal> check_money { get; set; }
        public string state { get; set; }
        public string creater { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string settle_men { get; set; }
        public Nullable<System.DateTime> settle_time { get; set; }
        public string hotel_code { get; set; }
        public string class_no { get; set; }
        public string remark { get; set; }
    }
}
