//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_event_room_price
    {
        public long id { get; set; }
        public string event_rule_code { get; set; }
        public string event_code { get; set; }
        public string hotel_code { get; set; }
        public Nullable<int> event_pattern { get; set; }
        public Nullable<decimal> value { get; set; }
        public string room_type_code { get; set; }
        public Nullable<short> check_in_type { get; set; }
    }
}
