//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_link
    {
        public long id { get; set; }
        public string link_code { get; set; }
        public string link_name { get; set; }
        public string weixin { get; set; }
        public string sina_weibo { get; set; }
        public string tc_weibo { get; set; }
        public System.DateTime server_due_time { get; set; }
        public System.DateTime use_due_time { get; set; }
        public string group_tel { get; set; }
        public string group_reserve_tel { get; set; }
        public Nullable<int> hotel_num { get; set; }
        public string group_addr { get; set; }
        public string group_introduce { get; set; }
        public string web_addr { get; set; }
        public int station_num { get; set; }
        public string remark { get; set; }
        public string registercode { get; set; }
        public string version { get; set; }
        public string version_type { get; set; }
        public Nullable<short> islink { get; set; }
    }
}
