//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_dept
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public string parent_id { get; set; }
        public short is_group_dept { get; set; }
        public string remark { get; set; }
    }
}
