//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_shift
    {
        public long id { get; set; }
        public string no { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string hotelcode { get; set; }
        public Nullable<short> whether { get; set; }
        public string creator { get; set; }
        public Nullable<decimal> acc_cash_coll { get; set; }
        public Nullable<decimal> acc_cash_out { get; set; }
        public Nullable<decimal> acc_bank_coll { get; set; }
        public Nullable<decimal> acc_bank_out { get; set; }
        public Nullable<decimal> acc_member { get; set; }
        public Nullable<decimal> acc_unit { get; set; }
        public Nullable<decimal> acc_medi { get; set; }
        public Nullable<decimal> acc_paid { get; set; }
        public Nullable<decimal> acc_free { get; set; }
        public Nullable<decimal> acc_other { get; set; }
        public Nullable<decimal> acc_cash_sum { get; set; }
        public Nullable<decimal> acc_bank_sum { get; set; }
        public Nullable<decimal> acc_gua_sum { get; set; }
        public Nullable<decimal> acc_room_sum { get; set; }
        public Nullable<decimal> acc_shop_sum { get; set; }
        public Nullable<decimal> acc_member_pay { get; set; }
        public Nullable<decimal> acc_full { get; set; }
        public Nullable<decimal> acc_half { get; set; }
        public Nullable<decimal> acc_hour { get; set; }
        public Nullable<decimal> acc_bed { get; set; }
        public Nullable<decimal> acc_discount { get; set; }
        public Nullable<decimal> acc_shop { get; set; }
        public Nullable<decimal> acc_compensation { get; set; }
        public Nullable<decimal> acc_meet { get; set; }
        public Nullable<decimal> acc_phone { get; set; }
        public Nullable<decimal> acc_kl { get; set; }
        public Nullable<decimal> acc_consump_other { get; set; }
        public Nullable<decimal> cash_cash_coll { get; set; }
        public Nullable<decimal> cash_cash_out { get; set; }
        public Nullable<decimal> cash_bank_coll { get; set; }
        public Nullable<decimal> cash_bank_out { get; set; }
        public Nullable<decimal> cash_member { get; set; }
        public Nullable<decimal> cash_unit { get; set; }
        public Nullable<decimal> cash_medi { get; set; }
        public Nullable<decimal> cash_paid { get; set; }
        public Nullable<decimal> cash_free { get; set; }
        public Nullable<decimal> cash_other { get; set; }
        public Nullable<decimal> cash_cash_sum { get; set; }
        public Nullable<decimal> cash_bank_sum { get; set; }
        public Nullable<decimal> cash_gua_sum { get; set; }
        public Nullable<decimal> cash_room_sum { get; set; }
        public Nullable<decimal> cash_shop_sum { get; set; }
        public Nullable<decimal> cash_member_pay { get; set; }
        public Nullable<decimal> cash_full { get; set; }
        public Nullable<decimal> cash_half { get; set; }
        public Nullable<decimal> cash_hour { get; set; }
        public Nullable<decimal> cash_bed { get; set; }
        public Nullable<decimal> cash_discount { get; set; }
        public Nullable<decimal> cash_shop { get; set; }
        public Nullable<decimal> cash_compensation { get; set; }
        public Nullable<decimal> cash_meet { get; set; }
        public Nullable<decimal> cash_phone { get; set; }
        public Nullable<decimal> cash_kl { get; set; }
        public Nullable<decimal> cash_consump_other { get; set; }
        public Nullable<decimal> handin_cash { get; set; }
        public Nullable<decimal> handin_bank { get; set; }
        public Nullable<decimal> y_onshift_cash { get; set; }
        public Nullable<decimal> y_onshift_bank { get; set; }
        public Nullable<decimal> y_shift_cash { get; set; }
        public Nullable<decimal> y_shift_bank { get; set; }
        public Nullable<decimal> y_nextshift_cash { get; set; }
        public Nullable<decimal> y_nextshift_bank { get; set; }
        public Nullable<decimal> s_onshift_cash { get; set; }
        public Nullable<decimal> s_onshift_bank { get; set; }
        public Nullable<decimal> s_shift_cash { get; set; }
        public Nullable<decimal> s_shift_bank { get; set; }
        public Nullable<decimal> s_nextshift_cash { get; set; }
        public Nullable<decimal> s_nextshift_bank { get; set; }
        public Nullable<decimal> cash_securities { get; set; }
        public Nullable<decimal> acc_securities { get; set; }
        public Nullable<decimal> cash_check { get; set; }
        public Nullable<decimal> cash_cy { get; set; }
        public Nullable<decimal> acc_check { get; set; }
        public Nullable<decimal> acc_cy { get; set; }
        public Nullable<decimal> acc_group { get; set; }
        public Nullable<decimal> acc_third_party { get; set; }
        public Nullable<decimal> cash_group { get; set; }
        public Nullable<decimal> cash_third_party { get; set; }
        public Nullable<decimal> memberpay_cash { get; set; }
        public Nullable<decimal> memberpay_bank { get; set; }
        public Nullable<decimal> memberpay_present { get; set; }
        public Nullable<decimal> pre_authorization { get; set; }
        public Nullable<decimal> cash_alipay { get; set; }
        public Nullable<decimal> cash_wxinpay { get; set; }
        public Nullable<decimal> acc_alipay { get; set; }
        public Nullable<decimal> acc_wxinpay { get; set; }
        public Nullable<decimal> memberpay_ali { get; set; }
        public Nullable<decimal> memberpay_wxin { get; set; }
        public Nullable<decimal> memberpay_others { get; set; }
    }
}
