//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_accounts
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string no { get; set; }
        public string room_no { get; set; }
        public Nullable<System.DateTime> consume_time { get; set; }
        public string business_type { get; set; }
        public string business_detail { get; set; }
        public Nullable<decimal> money { get; set; }
        public string custom_acc_no { get; set; }
        public string acc_attr { get; set; }
        public Nullable<short> red { get; set; }
        public string serial_no { get; set; }
        public Nullable<int> num { get; set; }
        public string voucher_no { get; set; }
        public string archives_no { get; set; }
        public string class_no { get; set; }
        public Nullable<double> room_night_no { get; set; }
        public string page { get; set; }
        public string creater { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string payment_method { get; set; }
        public Nullable<long> rich_id { get; set; }
        public string room_code { get; set; }
        public string source { get; set; }
        public string invoic_state { get; set; }
        public string invoic_shift { get; set; }
        public Nullable<System.DateTime> invoic_time { get; set; }
        public string invoic_creater { get; set; }
        public string transfer_state { get; set; }
        public Nullable<long> transfer_id { get; set; }
        public string split_state { get; set; }
        public Nullable<long> split_id { get; set; }
        public string merge_state { get; set; }
        public Nullable<long> merge_id { get; set; }
        public string pay_channel { get; set; }
        public Nullable<System.DateTime> valued_date { get; set; }
        public string pre_authorization { get; set; }
    }
}
