//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_unit_account
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string custom_acc { get; set; }
        public Nullable<short> custom_type { get; set; }
        public string card_no { get; set; }
        public string business_type { get; set; }
        public string business_detail { get; set; }
        public string order_no { get; set; }
        public string third { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<decimal> money { get; set; }
        public string creater { get; set; }
        public string class_no { get; set; }
        public string remark { get; set; }
        public string red { get; set; }
        public string rich_id { get; set; }
        public string voucher_no { get; set; }
        public Nullable<short> is_settle { get; set; }
        public Nullable<System.DateTime> settle_time { get; set; }
        public string source { get; set; }
        public string account_book_code { get; set; }
        public string acc_attr { get; set; }
    }
}
