//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_module_const
    {
        public int id { get; set; }
        public string perm_code { get; set; }
        public string tile_group { get; set; }
        public string data { get; set; }
        public string tile_type { get; set; }
        public string start_background { get; set; }
        public string end_background { get; set; }
        public string hotel_code { get; set; }
        public string remark { get; set; }
        public Nullable<short> sort { get; set; }
    }
}
