//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_sys_constant
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string first_value { get; set; }
        public string second_value { get; set; }
        public string parent_code { get; set; }
        public System.DateTime last_modi_time { get; set; }
        public string remark { get; set; }
        public Nullable<short> canMod { get; set; }
        public Nullable<short> parent_tab { get; set; }
        public Nullable<short> sort { get; set; }
        public string control_type { get; set; }
        public Nullable<short> islink { get; set; }
    }
}
