//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_checkinAnalysisByRoomtype
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public Nullable<System.DateTime> business_date { get; set; }
        public Nullable<System.DateTime> business_begintime { get; set; }
        public Nullable<System.DateTime> business_endtime { get; set; }
        public string room_type_code { get; set; }
        public Nullable<int> day_room_num { get; set; }
        public Nullable<int> month_room_num { get; set; }
        public Nullable<decimal> day_in_num { get; set; }
        public Nullable<decimal> day_rent_rate { get; set; }
        public Nullable<decimal> day_revenues { get; set; }
        public Nullable<decimal> day_ave_price { get; set; }
        public Nullable<decimal> month_in_num { get; set; }
        public Nullable<decimal> month_rent_rate { get; set; }
        public Nullable<decimal> month_revenues { get; set; }
        public Nullable<decimal> month_ave_price { get; set; }
    }
}
