//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_event_point_exch_room_log
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string event_code { get; set; }
        public Nullable<int> use_points { get; set; }
        public string room_type_title { get; set; }
        public Nullable<short> exch_room_num { get; set; }
        public Nullable<short> day_num { get; set; }
        public string hotel_name { get; set; }
        public string @operator { get; set; }
        public string room_type_code { get; set; }
        public string event_name { get; set; }
        public Nullable<short> check_in_type { get; set; }
        public Nullable<System.DateTime> exch_time { get; set; }
        public string acc_no { get; set; }
        public string vip_name { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<decimal> room_price { get; set; }
    }
}
