//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_updatelog
    {
        public long id { get; set; }
        public string s_version_no { get; set; }
        public string c_version_no { get; set; }
        public Nullable<System.DateTime> down_time { get; set; }
        public string file_name { get; set; }
        public Nullable<short> canupdate { get; set; }
        public Nullable<short> update_mode { get; set; }
        public string VerSionDesCrip { get; set; }
    }
}
