//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_business
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public System.DateTime business_date { get; set; }
        public System.DateTime business_start_datetime { get; set; }
        public System.DateTime business_end_datetime { get; set; }
        public Nullable<decimal> full_room_fee { get; set; }
        public Nullable<decimal> half_room_fee { get; set; }
        public Nullable<decimal> hour_room_fee { get; set; }
        public Nullable<decimal> discount_room_fee { get; set; }
        public Nullable<decimal> extra_room_fee { get; set; }
        public Nullable<decimal> minbar_fee { get; set; }
        public Nullable<decimal> bathroom_fee { get; set; }
        public Nullable<decimal> damages_fee { get; set; }
        public Nullable<decimal> meeting_fee { get; set; }
        public Nullable<decimal> tel_fee { get; set; }
        public Nullable<decimal> others_fee { get; set; }
        public Nullable<decimal> rich_fee { get; set; }
        public Nullable<decimal> stage_cash { get; set; }
        public Nullable<decimal> stage_card { get; set; }
        public Nullable<decimal> stage_cheque { get; set; }
        public Nullable<decimal> stage_member_card { get; set; }
        public Nullable<decimal> stage_ledge { get; set; }
        public Nullable<decimal> stage_free { get; set; }
        public Nullable<decimal> stage_voucher { get; set; }
        public Nullable<decimal> stage_others { get; set; }
        public Nullable<decimal> stage_old_balance { get; set; }
        public Nullable<decimal> member_cash { get; set; }
        public Nullable<decimal> member_card { get; set; }
        public Nullable<decimal> member_present { get; set; }
        public Nullable<decimal> member_count { get; set; }
        public Nullable<decimal> unit_medi_cash { get; set; }
        public Nullable<decimal> unit_medi_card { get; set; }
        public Nullable<decimal> unit_medi_cheque { get; set; }
        public Nullable<decimal> turn_receivables_unit { get; set; }
        public Nullable<decimal> turn_receivables_medi { get; set; }
        public Nullable<decimal> receivable_recovery_cash { get; set; }
        public Nullable<decimal> receivable_recovery_card { get; set; }
        public Nullable<decimal> receivable_recovery_cheque { get; set; }
        public Nullable<decimal> receivable_recovery_advance { get; set; }
        public Nullable<decimal> all_room_total { get; set; }
        public Nullable<decimal> repair_room_total { get; set; }
        public Nullable<decimal> available_room_total { get; set; }
        public Nullable<decimal> team_room_total { get; set; }
        public Nullable<decimal> private_room_total { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<decimal> third_consume { get; set; }
        public Nullable<decimal> catering_fee { get; set; }
        public Nullable<decimal> ali_pay { get; set; }
        public Nullable<decimal> wechat_pay { get; set; }
        public Nullable<decimal> receivable_recovery_zdy { get; set; }
        public Nullable<decimal> receivable_recovery_wxin { get; set; }
        public Nullable<decimal> receivable_recovery_alipay { get; set; }
        public Nullable<decimal> unit_medi_ali { get; set; }
        public Nullable<decimal> unit_medi_wxin { get; set; }
        public Nullable<decimal> member_ali { get; set; }
        public Nullable<decimal> member_wxin { get; set; }
        public Nullable<decimal> member_others { get; set; }
    }
}
