//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_standard
    {
        public long id { get; set; }
        public string standard_code { get; set; }
        public string standard_name { get; set; }
        public Nullable<int> day_half_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public Nullable<System.DateTime> full_time { get; set; }
        public string charge_way { get; set; }
        public string remark { get; set; }
        public string creater { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> day_full_time { get; set; }
        public string full_model { get; set; }
        public string out_room_model { get; set; }
        public Nullable<int> full_length { get; set; }
        public Nullable<int> start_time { get; set; }
        public Nullable<int> is_top_flag { get; set; }
        public string hotel_code { get; set; }
        public Nullable<int> first_confirm_full_length { get; set; }
        public string second_confirm_full_mode { get; set; }
        public Nullable<System.DateTime> second_confirm_full_time { get; set; }
        public Nullable<int> second_confirm_full_length { get; set; }
        public string first_confirm_full_mode { get; set; }
        public Nullable<System.DateTime> first_confirm_full_time { get; set; }
    }
}
