//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_h_log
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string object_id { get; set; }
        public string object_title { get; set; }
        public string request_ip { get; set; }
        public string request_url { get; set; }
        public string sessionId { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string scope_id { get; set; }
        public string scope_title { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
