//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_m_pointexchangerule
    {
        public long id { get; set; }
        public string giftvoucher { get; set; }
        public Nullable<decimal> voucher_money { get; set; }
        public Nullable<int> need_point { get; set; }
        public Nullable<short> exchange_type { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> last_modtime { get; set; }
        public string @operator { get; set; }
        public Nullable<long> activitiesid { get; set; }
    }
}
