//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_m_changecardlog
    {
        public long id { get; set; }
        public string hotelCode { get; set; }
        public Nullable<long> memberId { get; set; }
        public string oldCardNo { get; set; }
        public string newCardNo { get; set; }
        public Nullable<System.DateTime> changeTime { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
    }
}
