//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_m_pointsrule
    {
        public long id { get; set; }
        public Nullable<short> order_channel { get; set; }
        public Nullable<int> limit_money { get; set; }
        public Nullable<short> activity_mode { get; set; }
        public string remark { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> last_modtime { get; set; }
        public Nullable<long> activitiesid { get; set; }
        public Nullable<short> isenable { get; set; }
    }
}
