//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_m_pointlog
    {
        public long id { get; set; }
        public string hotelCode { get; set; }
        public Nullable<long> memberId { get; set; }
        public string cardNumber { get; set; }
        public string roomNo { get; set; }
        public Nullable<System.DateTime> checkInTime { get; set; }
        public Nullable<System.DateTime> checkOutTime { get; set; }
        public string pricePlanCode { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> point { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> operateTime { get; set; }
        public Nullable<int> pointType { get; set; }
        public Nullable<decimal> money { get; set; }
        public string order_no { get; set; }
    }
}
