//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_m_amountpresentrule
    {
        public long id { get; set; }
        public Nullable<long> storevalue_modeid { get; set; }
        public Nullable<decimal> present_begin { get; set; }
        public Nullable<decimal> present_end { get; set; }
        public Nullable<decimal> present_amount { get; set; }
        public Nullable<int> point { get; set; }
    }
}
