//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_r_special_room
    {
        public long id { get; set; }
        public string planname { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> remind { get; set; }
        public Nullable<int> half_price_time { get; set; }
        public Nullable<int> full_price_time { get; set; }
        public string hotel_code { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public Nullable<int> ore_than_in { get; set; }
        public Nullable<int> ore_than_price { get; set; }
        public string remark { get; set; }
        public Nullable<int> breakfast_num { get; set; }
        public string plan_code { get; set; }
        public string limit_logo { get; set; }
        public string charge_way { get; set; }
        public Nullable<int> is_top_flag { get; set; }
    }
}
