//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_r_room
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string room_code { get; set; }
        public string room_no { get; set; }
        public string building { get; set; }
        public string floor { get; set; }
        public string room_type_code { get; set; }
        public string room_state_code { get; set; }
        public string tel_ext { get; set; }
        public string outside_line { get; set; }
        public Nullable<short> publish { get; set; }
        public string toward { get; set; }
        public Nullable<short> road { get; set; }
        public Nullable<short> window { get; set; }
        public Nullable<short> quiet { get; set; }
        public Nullable<short> smokeless { get; set; }
        public string creater { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> last_time { get; set; }
        public string remark { get; set; }
        public string lock_info { get; set; }
        public string door_lock_build { get; set; }
        public string door_lock_num { get; set; }
        public string door_lock_floor { get; set; }
        public Nullable<short> reverse_open { get; set; }
        public Nullable<int> guest_num { get; set; }
        public Nullable<int> card_num { get; set; }
        public string lock_parametero { get; set; }
        public string lock_parametert { get; set; }
        public string lock_parameters { get; set; }
        public string lock_parameterf { get; set; }
        public string lock_parameterv { get; set; }
        public string interface_code { get; set; }
        public Nullable<short> lock_room { get; set; }
        public string room_service_state_code { get; set; }
        public Nullable<int> lock_type { get; set; }
        public string lock_room_seria_no { get; set; }
        public string lock_room_sequential_no { get; set; }
    }
}
