//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_r_room_type
    {
        public long id { get; set; }
        public string room_type_code { get; set; }
        public string room_type_title { get; set; }
        public Nullable<decimal> market_price { get; set; }
        public Nullable<decimal> individual_price { get; set; }
        public Nullable<decimal> agreement_price { get; set; }
        public Nullable<decimal> members_price { get; set; }
        public Nullable<decimal> mediation_price { get; set; }
        public Nullable<int> over_reserve_num { get; set; }
        public Nullable<int> check_in_num { get; set; }
        public string information { get; set; }
        public Nullable<int> reservation { get; set; }
        public Nullable<decimal> first_deposit { get; set; }
        public Nullable<decimal> next_deposit { get; set; }
        public Nullable<decimal> hours_price { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
    }
}
