//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_r_hour_room
    {
        public long id { get; set; }
        public string z_code { get; set; }
        public string z_name { get; set; }
        public Nullable<int> half_price_time { get; set; }
        public Nullable<int> full_price_time { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> more_than { get; set; }
        public Nullable<int> more_than_normal { get; set; }
        public Nullable<short> isdisable { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
        public Nullable<int> breakfast_num { get; set; }
        public string limit_logo { get; set; }
        public Nullable<decimal> time_length { get; set; }
        public Nullable<int> is_top_flag { get; set; }
    }
}
