//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_r_anomaly
    {
        public long id { get; set; }
        public string anomalyTypeCode { get; set; }
        public string roomCode { get; set; }
        public string oldRoom { get; set; }
        public string newRoom { get; set; }
        public string oldPricePlan { get; set; }
        public string newPricePlan { get; set; }
        public string oldPrice { get; set; }
        public string newPrice { get; set; }
        public string employee { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
    }
}
