//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_r_global_lockpara
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string interface_code { get; set; }
        public string lock_serial_no { get; set; }
        public string lock_card_no { get; set; }
        public string lock_sequential_no { get; set; }
        public string lock_subcard_no { get; set; }
        public string lock_max_serial_no { get; set; }
        public string lock_max_sequential_no { get; set; }
        public string lock_max_card_no { get; set; }
        public string lock_max_subcard_no { get; set; }
    }
}
