//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_guests_goods_management
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public Nullable<System.DateTime> storage_time { get; set; }
        public string googs_type { get; set; }
        public string googs_name { get; set; }
        public string guest_name { get; set; }
        public string mobile { get; set; }
        public string room_no { get; set; }
        public string reference_price { get; set; }
        public string remark { get; set; }
        public string store_operator { get; set; }
        public Nullable<System.DateTime> receive_time { get; set; }
        public string receive_operator { get; set; }
        public Nullable<int> is_receive { get; set; }
        public string order_no { get; set; }
    }
}
