//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_male_model
    {
        public string code { get; set; }
        public string name { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string creater { get; set; }
        public string remark { get; set; }
        public string hotelcode { get; set; }
        public long id { get; set; }
    }
}
