//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_member
    {
        public long id { get; set; }
        public string archives_no { get; set; }
        public string acc_no { get; set; }
        public string card_no { get; set; }
        public string card_serial_no { get; set; }
        public string password { get; set; }
        public Nullable<int> total_score { get; set; }
        public Nullable<decimal> total_consume { get; set; }
        public Nullable<int> total_exchange { get; set; }
        public Nullable<decimal> total_recharge { get; set; }
        public Nullable<decimal> total_money { get; set; }
        public string member_type { get; set; }
        public Nullable<short> member_state { get; set; }
        public string tel { get; set; }
        public string source { get; set; }
        public string weixin { get; set; }
        public string open_id { get; set; }
        public Nullable<decimal> overage { get; set; }
        public Nullable<decimal> present { get; set; }
        public Nullable<System.DateTime> invalid_date { get; set; }
        public Nullable<System.DateTime> grant_date { get; set; }
        public string salesman { get; set; }
        public Nullable<System.DateTime> last_mod_time { get; set; }
        public Nullable<int> remain_point { get; set; }
        public Nullable<decimal> freeze_money { get; set; }
        public Nullable<decimal> consume_money { get; set; }
        public Nullable<decimal> overdraw_amount { get; set; }
        public string intr_arch_no { get; set; }
        public string hotel_code { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> isissue { get; set; }
        public int isgroup { get; set; }
        public string creater { get; set; }
    }
}
