//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_pay_method
    {
        public long id { get; set; }
        public string pay_code { get; set; }
        public string pay_name { get; set; }
        public string level { get; set; }
        public string system_default { get; set; }
        public Nullable<short> ischarge { get; set; }
        public Nullable<short> isrefund { get; set; }
        public string hotel_code { get; set; }
        public Nullable<short> isjf { get; set; }
    }
}
