//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_reserve
    {
        public long id { get; set; }
        public string order_no { get; set; }
        public string name { get; set; }
        public string cred_no { get; set; }
        public string mobile { get; set; }
        public string groupname { get; set; }
        public string menber_no { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public Nullable<int> daynum { get; set; }
        public string channel { get; set; }
        public string market_type { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string creater { get; set; }
        public string hotelcode { get; set; }
        public string salesman { get; set; }
        public string unit_acc_no { get; set; }
        public string medi_code { get; set; }
        public Nullable<short> isgroup { get; set; }
        public string standard_type { get; set; }
        public string standard { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> keep_time { get; set; }
        public string activity_code { get; set; }
        public string order_source { get; set; }
        public string order_type { get; set; }
        public string third_order_no { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<decimal> room_credit_limit { get; set; }
        public string guarantee_type { get; set; }
        public Nullable<decimal> guarantee_amount { get; set; }
        public Nullable<System.DateTime> last_arrival_datetime { get; set; }
        public string batch_no { get; set; }
        public Nullable<decimal> gift_flash_limit { get; set; }
        public string receptionist { get; set; }
    }
}
