//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_member_type
    {
        public long id { get; set; }
        public string type_code { get; set; }
        public string type_name { get; set; }
        public string level { get; set; }
        public Nullable<short> recharge { get; set; }
        public Nullable<decimal> card_cost { get; set; }
        public string reserve_time { get; set; }
        public Nullable<short> overdraw { get; set; }
        public Nullable<short> integral { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
        public string accrule_code { get; set; }
        public string checkin_standard { get; set; }
        public string system_default { get; set; }
        public string link_code { get; set; }
    }
}
