//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_reserve_room
    {
        public long id { get; set; }
        public string order_no { get; set; }
        public string roomtype_code { get; set; }
        public Nullable<int> amount { get; set; }
        public string unit_acc_no { get; set; }
        public Nullable<decimal> price { get; set; }
        public string room_code { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string hotelcode { get; set; }
        public string state { get; set; }
        public Nullable<int> is_handprice { get; set; }
        public string main_order_no { get; set; }
        public Nullable<int> breakfast { get; set; }
        public string activity_code { get; set; }
        public string event_type { get; set; }
    }
}
