//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_notebook
    {
        public string platform { get; set; }
        public string tel { get; set; }
        public string adress { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string remark { get; set; }
        public string hotelcode { get; set; }
        public long id { get; set; }
    }
}
