//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_protocol_unit
    {
        public long id { get; set; }
        public string hotel_code { get; set; }
        public string archives_no { get; set; }
        public string name { get; set; }
        public string spell { get; set; }
        public string parent_archives_no { get; set; }
        public string check_out_time { get; set; }
        public string linkman { get; set; }
        public string mobile { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string standard_type { get; set; }
        public string standard { get; set; }
        public string addr { get; set; }
        public Nullable<decimal> attach_amount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string contract_no { get; set; }
        public Nullable<System.DateTime> contract_begin { get; set; }
        public Nullable<System.DateTime> contract_end { get; set; }
        public string bank_account { get; set; }
        public string user_id { get; set; }
        public Nullable<short> secrecy { get; set; }
        public string creater { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string remark { get; set; }
        public Nullable<int> breakfast_num { get; set; }
        public string type_code { get; set; }
        public Nullable<short> is_disable { get; set; }
        public string source { get; set; }
    }
}
