//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_order_rela
    {
        public long id { get; set; }
        public string rela_code { get; set; }
        public string order_no { get; set; }
        public string invoic_state { get; set; }
        public string in_state { get; set; }
        public string source { get; set; }
        public string main_mark { get; set; }
        public string group_mark { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> invoic_time { get; set; }
        public string invoic_shift { get; set; }
        public string invoic_creater { get; set; }
        public string hotelcode { get; set; }
        public string ledger { get; set; }
        public string go_why { get; set; }
        public string related_order_no { get; set; }
    }
}
