//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_clock
    {
        public long id { get; set; }
        public Nullable<int> is_open { get; set; }
        public string room { get; set; }
        public Nullable<System.DateTime> clock_time { get; set; }
        public string name { get; set; }
        public string room_mobile { get; set; }
        public string tel { get; set; }
        public string room_type { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public string remark { get; set; }
        public string hotelcode { get; set; }
    }
}
