//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_breakfast_voucher
    {
        public long id { get; set; }
        public string breakfast_no { get; set; }
        public string hotel_code { get; set; }
        public string room_no { get; set; }
        public string state { get; set; }
        public Nullable<int> num { get; set; }
        public string standard_name { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string remark { get; set; }
        public string order_no { get; set; }
        public System.DateTime valid_date { get; set; }
        public string creater { get; set; }
        public string shift_no { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> roomprice { get; set; }
    }
}
