//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_guest
    {
        public long id { get; set; }
        public string archives_no { get; set; }
        public string name { get; set; }
        public string spell { get; set; }
        public string cert_type { get; set; }
        public string cert_no { get; set; }
        public string nationality { get; set; }
        public short sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public string creater { get; set; }
        public System.DateTime create_time { get; set; }
        public string regions { get; set; }
        public string address { get; set; }
        public string hobby { get; set; }
        public string company { get; set; }
        public string car_no { get; set; }
        public string need { get; set; }
        public Nullable<short> black { get; set; }
        public string black_reason { get; set; }
        public Nullable<System.DateTime> black_time { get; set; }
        public string black_creater { get; set; }
        public string remark { get; set; }
        public string nation { get; set; }
    }
}
