//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_history_order
    {
        public long id { get; set; }
        public string checkInno { get; set; }
        public string hotelcode { get; set; }
        public string name { get; set; }
        public string spell { get; set; }
        public string type { get; set; }
        public string idnumber { get; set; }
        public string email { get; set; }
        public string roomno { get; set; }
        public string roomtypecode { get; set; }
        public string standard_type { get; set; }
        public string standard { get; set; }
        public Nullable<decimal> price { get; set; }
        public string market_type { get; set; }
        public string channel { get; set; }
        public Nullable<System.DateTime> checkIntime { get; set; }
        public Nullable<System.DateTime> duecheckouttime { get; set; }
        public Nullable<int> days { get; set; }
        public string info_secret { get; set; }
        public string address { get; set; }
        public string other_info { get; set; }
        public string call_level { get; set; }
        public Nullable<short> account_into { get; set; }
        public Nullable<short> call_free { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string unit_acc_no { get; set; }
        public string inorder { get; set; }
        public string inoperator { get; set; }
        public string salesman { get; set; }
        public string remark { get; set; }
        public string outorder { get; set; }
        public string outoperator { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public Nullable<decimal> roomcharge { get; set; }
        public Nullable<decimal> other { get; set; }
        public string member_code { get; set; }
        public string invoice_no { get; set; }
        public string park_no { get; set; }
        public Nullable<short> breakfast { get; set; }
        public string activity_code { get; set; }
        public string room_manage_state { get; set; }
        public string room_manage_remark { get; set; }
        public string medi_code { get; set; }
        public Nullable<int> is_handprice { get; set; }
        public Nullable<short> need_breakfast { get; set; }
        public string member_acc_no { get; set; }
        public string invoic_class_no { get; set; }
        public string invoic_operator { get; set; }
        public Nullable<System.DateTime> invoic_time { get; set; }
        public string room_code { get; set; }
        public string order_source { get; set; }
        public string order_type { get; set; }
        public string third_order_no { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<decimal> room_credit_limit { get; set; }
        public Nullable<decimal> gift_flash_limit { get; set; }
        public string receptionist { get; set; }
        public short leave_attr { get; set; }
        public string leave_operator { get; set; }
        public Nullable<System.DateTime> leave_time { get; set; }
        public string leave_class_no { get; set; }
    }
}
