//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_parking_management
    {
        public long id { get; set; }
        public string parking_no { get; set; }
        public string order_no { get; set; }
        public string hotel_code { get; set; }
        public string room_code { get; set; }
        public Nullable<System.DateTime> register_time { get; set; }
        public string room_no { get; set; }
        public string archives_no { get; set; }
        public string name { get; set; }
        public string tel_no { get; set; }
        public string car_no { get; set; }
        public string parking_lot { get; set; }
        public Nullable<System.DateTime> point_time { get; set; }
        public Nullable<decimal> parking_rate { get; set; }
        public string @operator { get; set; }
        public Nullable<int> guest_type { get; set; }
        public Nullable<int> parking_type { get; set; }
        public Nullable<int> auto_entry_account { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string shif_no { get; set; }
    }
}
