//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_u_team
    {
        public long id { get; set; }
        public string team_name { get; set; }
        public string rela_code { get; set; }
        public string male_code { get; set; }
        public string hotelcode { get; set; }
        public string name { get; set; }
        public string cred_no { get; set; }
        public string mobile { get; set; }
        public string menber_no { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public Nullable<int> daynum { get; set; }
        public string channel { get; set; }
        public string market_type { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string creater { get; set; }
        public string unit_acc_no { get; set; }
        public Nullable<short> isgroup { get; set; }
        public string standard_type { get; set; }
        public string standard { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> keep_time { get; set; }
        public string activity_code { get; set; }
        public string receptionist { get; set; }
    }
}
