//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_inventory_detail
    {
        public long id { get; set; }
        public string inve_code { get; set; }
        public string goods_code { get; set; }
        public Nullable<int> store_num { get; set; }
        public Nullable<int> inve_num { get; set; }
        public decimal price { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
    }
}
