//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_goods_store
    {
        public long id { get; set; }
        public string goods_code { get; set; }
        public Nullable<double> store_num { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string warehouse_code { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
    }
}
