//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_store_allot
    {
        public long id { get; set; }
        public string allot_code { get; set; }
        public string out_ware_code { get; set; }
        public string in_ware_code { get; set; }
        public System.DateTime allot_time { get; set; }
        public string @operator { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
        public string creater { get; set; }
    }
}
