//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_goods
    {
        public long id { get; set; }
        public string goods_code { get; set; }
        public string barcode { get; set; }
        public string goods_title { get; set; }
        public string spell { get; set; }
        public string cate_code { get; set; }
        public string unit_code { get; set; }
        public Nullable<int> maximum { get; set; }
        public Nullable<int> minimum { get; set; }
        public Nullable<short> stop { get; set; }
        public Nullable<short> sale { get; set; }
        public Nullable<decimal> ref_price { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<short> mini_sale { get; set; }
        public Nullable<decimal> mini_price { get; set; }
        public Nullable<decimal> mini_in_price { get; set; }
        public Nullable<short> mini_price_consult { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
        public string sale_size { get; set; }
        public Nullable<short> sale_byzero { get; set; }
    }
}
