//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_supplier_schedule
    {
        public long id { get; set; }
        public string initial_id { get; set; }
        public string hotel_code { get; set; }
        public System.DateTime create_time { get; set; }
        public string supplier_code { get; set; }
        public Nullable<decimal> initial_amount { get; set; }
        public Nullable<decimal> purchase_amount { get; set; }
        public Nullable<decimal> return_amount { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<decimal> supplier_refund { get; set; }
        public Nullable<decimal> initial_balance { get; set; }
    }
}
