//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_loss_overflow_detail
    {
        public long id { get; set; }
        public string voucher_code { get; set; }
        public string goods_code { get; set; }
        public Nullable<double> num { get; set; }
    }
}
