//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_goods_in
    {
        public long id { get; set; }
        public string in_code { get; set; }
        public string supplier_code { get; set; }
        public string warehouse_code { get; set; }
        public System.DateTime in_time { get; set; }
        public string in_type { get; set; }
        public Nullable<decimal> in_money { get; set; }
        public string @operator { get; set; }
        public string purc_dept_code { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
        public Nullable<decimal> rebate { get; set; }
        public string creater { get; set; }
    }
}
