//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_w_supplier
    {
        public long id { get; set; }
        public string supplier_code { get; set; }
        public string supplier_title { get; set; }
        public short stop { get; set; }
        public string linkman { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string bank { get; set; }
        public string account_name { get; set; }
        public string account_no { get; set; }
        public string remark { get; set; }
        public string hotel_code { get; set; }
    }
}
