//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Repository.MappingEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOVERSEASGUEST
    {
        public int ID { get; set; }
        public string FCODE { get; set; }
        public string FENFIRSTNAME { get; set; }
        public string FENLASTNAME { get; set; }
        public string FNAME { get; set; }
        public string FSEX { get; set; }
        public string FFOLK { get; set; }
        public string FBIRTHDAY { get; set; }
        public string FNATIONALITY { get; set; }
        public string FPAPERTYPE { get; set; }
        public string FPAPERCODE { get; set; }
        public string FVISATYPE { get; set; }
        public string FCANTONCODE { get; set; }
        public string FVISACODE { get; set; }
        public string FSTAYDATE { get; set; }
        public string FVISAOFFICE { get; set; }
        public string FENTERDATE { get; set; }
        public string FRECEIVEOFFICE { get; set; }
        public string FENTERPORT { get; set; }
        public string FLIVEINTIME { get; set; }
        public string FLIVEINROOMCODE { get; set; }
        public Nullable<int> FISLEAVE { get; set; }
        public string FLEAVETIME { get; set; }
        public string FWHEREGOTO { get; set; }
        public string FCREDITCARDTYPE { get; set; }
        public string FCREDITCARDCODE { get; set; }
        public Nullable<int> FPHOTOFILESIZE { get; set; }
        public byte[] FPHOTOIMAGEBYTES { get; set; }
        public string FREMARK { get; set; }
        public Nullable<int> FGUESTTYPE { get; set; }
        public Nullable<int> FFLAG { get; set; }
        public string FOPTIME { get; set; }
    }
}
